# Generated by Django 3.1.1 on 2020-10-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201018_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timeEnd',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timeStart',
        ),
    ]
