# Generated by Django 3.1.1 on 2020-10-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201018_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
    ]
